-- MySQL Script generated by MySQL Workbench
-- seg 15 set 2025 14:22:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(2150) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `status` CHAR(1) NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(100) NOT NULL,
  `disponivel` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(90) NOT NULL,
  `ingredientes` VARCHAR(300) NOT NULL,
  `valor_un` DECIMAL(10,2) NOT NULL,
  `observacoes` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `idproduto_UNIQUE` (`idproduto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_carrinho` (
  `idcarrinho` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `valor_entrega` DECIMAL(10,2) NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `valor_pago` DECIMAL(10,2) NOT NULL,
  `troco` DECIMAL(10,2) NOT NULL,
  `data_hora` DATETIME NOT NULL,
  PRIMARY KEY (`idcarrinho`),
  UNIQUE INDEX `idcarrinho_UNIQUE` (`idcarrinho` ASC) VISIBLE,
  INDEX `fk_carrinho_cliente_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`tb_cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_entrega` (
  `identrega` INT NOT NULL AUTO_INCREMENT,
  `entregador` VARCHAR(90) NOT NULL,
  `idcarrinho` INT NOT NULL,
  PRIMARY KEY (`identrega`),
  UNIQUE INDEX `identrega_UNIQUE` (`identrega` ASC) VISIBLE,
  INDEX `fk_entrega_carrinho1_idx` (`idcarrinho` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_carrinho1`
    FOREIGN KEY (`idcarrinho`)
    REFERENCES `mydb`.`tb_carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_item_venda` (
  `idcarrinho` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idcarrinho`, `idproduto`),
  INDEX `fk_produto_has_carrinho_carrinho1_idx` (`idcarrinho` ASC) VISIBLE,
  INDEX `fk_produto_has_carrinho_produto1_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_carrinho_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `mydb`.`tb_produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_carrinho_carrinho1`
    FOREIGN KEY (`idcarrinho`)
    REFERENCES `mydb`.`tb_carrinho` (`idcarrinho`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tb_produto (foto, disponivel, tipo, nome, ingredientes, valor_un, observacoes)
VALUES
('fotos/teste.png', '10', 'Bolo', 'Bolo de morango', 'Massa branca, mousse branca, morangos, creme gelado com morangos', 15.00, 'Item popular no cardápio'),

('fotos/teste.png', '12', 'Bolo', 'Ganache de limão', 'Massa branca, mousse branco, creme gelado de limão', 15.00, 'Refrescante e cítrico'),

('fotos/teste.png', '10', 'Bolo', 'Bolo de chocolate amargo', 'Massa de chocolate amargo, trufado de chocolate branco, chocolate 100% cacau', 15.00, 'Intenso e sofisticado'),

('fotos/teste.png', '11', 'Bolo', 'Trufado de cereja', 'Massa de chocolate, mousse de chocolate com cereja, trufado de chocolate ao leite', 15.00, 'Com toque frutado e doce');


INSERT INTO tb_cliente (email, senha, nome, telefone, endereco, status, tipo) 
VALUES 
  ('Todyy@gmail.com', SHA2('todyy', 256), 'Iasmin', '123456789', 'rua 2314', 'd', 'c'),
  ('lucas@gmail.com', SHA2('lucas', 256), 'Lucas Silva', '987654321', 'av. Paulista, 1500', 'd', 'c'),
  ('jose@example.com', SHA2('jose', 256), 'José Pereira', '1122334455', 'rua 4567', 'd', 'c'),
  ('mariana@hotmail.com', SHA2('mariana', 256), 'Mariana Costa', '9988776655', 'rua das Flores, 1000', 'd', 'c'),
  ('bruna@outlook.com', SHA2('bruna', 256), 'Bruna Almeida', '6677889900', 'av. Rio Branco, 200', 'd', 'c'),
  ('fabio@site.com', SHA2('fabio', 256), 'Fábio Costa', '5556667777', 'rua Jardim, 32', 'd', 'c'),
  ('camila@dominio.com', SHA2('camila', 256), 'Camila Souza', '4445556666', 'rua do Sol, 850', 'd', 'c'),
  ('pedro@exemplo.com', SHA2('pedro', 256), 'Pedro Lima', '3334445555', 'av. Central, 50', 'd', 'c'),
  ('ana@teste.com', SHA2('ana', 256), 'Ana Oliveira', '2223334444', 'rua das Palmeiras, 22', 'd', 'c'),
  ('roberto@company.com', SHA2('roberto', 256), 'Roberto Martins', '1212121212', 'rua do Parque, 123', 'd', 'c'),
  ('larissa@webmail.com', SHA2('larissa', 256), 'Larissa Santos', '1987654321', 'av. Brasil, 750', 'd', 'c'),
  ('andrea@admin.com', SHA2('andrea', 256), 'Andrea Silva', '6667778888', 'rua dos Gestores, 11', 'd', 'g'),
  ('rodrigo@manager.com', SHA2('rodrigo', 256), 'Rodrigo Carvalho', '9998887777', 'av. Empresarial, 40', 'd', 'g'),
  ('patricia@corporate.com', SHA2('patricia', 256), 'Patricia Gomes', '5557779999', 'rua Executiva, 78', 'd', 'g'),
  ('alex@adminsite.com', SHA2('alex', 256), 'Alex Ferreira', '4448887777', 'av. Liderança, 50', 'd', 'g'),
  ('toddy@gmail.com', SHA2('toddy', 256), 'Iasminny', '4228887777', 'av. Onçinha, 59', 'd', 'g'),
  ('sandy@gmail.com', SHA2('sandy', 256), 'Sandy', '444845377', 'av Barracão, 50', 'd', 'g'),
  ('izabella@gmail.com', SHA2('izabella', 256), 'Izabella', '4446687777', 'rua itiopo, 50', 'd', 'g');
