-- MySQL Script generated by MySQL Workbench
-- seg 15 set 2025 14:22:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(2150) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `status` CHAR(1) NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(100) NOT NULL,
  `disponivel` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(90) NOT NULL,
  `ingredientes` VARCHAR(300) NOT NULL,
  `valor_un` DECIMAL(10,2) NOT NULL,
  `observacoes` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `idproduto_UNIQUE` (`idproduto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_carrinho` (
  `idcarrinho` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `valor_entrega` DECIMAL(10,2) NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `valor_pago` DECIMAL(10,2) NOT NULL,
  `troco` DECIMAL(10,2) NOT NULL,
  `data_hora` DATETIME NOT NULL,
  PRIMARY KEY (`idcarrinho`),
  UNIQUE INDEX `idcarrinho_UNIQUE` (`idcarrinho` ASC) VISIBLE,
  INDEX `fk_carrinho_cliente_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`tb_cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_entrega` (
  `identrega` INT NOT NULL AUTO_INCREMENT,
  `entregador` VARCHAR(90) NOT NULL,
  `idcarrinho` INT NOT NULL,
  PRIMARY KEY (`identrega`),
  UNIQUE INDEX `identrega_UNIQUE` (`identrega` ASC) VISIBLE,
  INDEX `fk_entrega_carrinho1_idx` (`idcarrinho` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_carrinho1`
    FOREIGN KEY (`idcarrinho`)
    REFERENCES `mydb`.`tb_carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_item_venda` (
  `idcarrinho` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idcarrinho`, `idproduto`),
  INDEX `fk_produto_has_carrinho_carrinho1_idx` (`idcarrinho` ASC) VISIBLE,
  INDEX `fk_produto_has_carrinho_produto1_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_carrinho_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `mydb`.`tb_produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_carrinho_carrinho1`
    FOREIGN KEY (`idcarrinho`)
    REFERENCES `mydb`.`tb_carrinho` (`idcarrinho`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tb_produto (foto, disponivel, tipo, nome, ingredientes, valor_un, observacoes)
VALUES
('fotos/teste.png', '10', 'Bolo', 'Bolo de morango', 'Massa branca, mousse branca, morangos, creme gelado com morangos', 15.00, 'Item popular no cardápio'),

('fotos/teste.png', '12', 'Bolo', 'Ganache de limão', 'Massa branca, mousse branco, creme gelado de limão', 15.00, 'Refrescante e cítrico'),

('fotos/teste.png', '10', 'Bolo', 'Bolo de chocolate amargo', 'Massa de chocolate amargo, trufado de chocolate branco, chocolate 100% cacau', 15.00, 'Intenso e sofisticado'),

('fotos/teste.png', '11', 'Bolo', 'Trufado de cereja', 'Massa de chocolate, mousse de chocolate com cereja, trufado de chocolate ao leite', 15.00, 'Com toque frutado e doce');