-- MySQL Script generated by MySQL Workbench
-- qui 24 abr 2025 09:18:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idlogin`),
  UNIQUE INDEX `idlogin_UNIQUE` (`idlogin` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `quantidade` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(90) NOT NULL,
  `ingredientes` VARCHAR(300) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `idproduto_UNIQUE` (`idproduto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrinho` (
  `idcarrinho` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(90) NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_un` DECIMAL(10,2) NOT NULL,
  `valor_entrega` DECIMAL(10,2) NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `valor_pago` DECIMAL(10,2) NOT NULL,
  `troco` DECIMAL(10,2) NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `idcliente` INT NOT NULL,
  PRIMARY KEY (`idcarrinho`, `idcliente`),
  UNIQUE INDEX `idcarrinho_UNIQUE` (`idcarrinho` ASC) VISIBLE,
  INDEX `fk_carrinho_cliente1_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entrega` (
  `identrega` INT NOT NULL AUTO_INCREMENT,
  `idcliente` VARCHAR(45) NOT NULL,
  `idcarrinho` INT NOT NULL,
  PRIMARY KEY (`identrega`, `idcarrinho`, `idcliente`),
  UNIQUE INDEX `identrega_UNIQUE` (`identrega` ASC) VISIBLE,
  INDEX `fk_entrega_carrinho1_idx` (`idcarrinho` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_carrinho1`
    FOREIGN KEY (`idcarrinho`)
    REFERENCES `mydb`.`carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto_has_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto_has_carrinho` (
  `produto_idproduto` INT NOT NULL,
  `carrinho_idcarrinho` INT NOT NULL,
  PRIMARY KEY (`produto_idproduto`, `carrinho_idcarrinho`),
  INDEX `fk_produto_has_carrinho_carrinho1_idx` (`carrinho_idcarrinho` ASC) VISIBLE,
  INDEX `fk_produto_has_carrinho_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_carrinho_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_carrinho_carrinho1`
    FOREIGN KEY (`carrinho_idcarrinho`)
    REFERENCES `mydb`.`carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
