-- MySQL Script generated by MySQL Workbench
-- seg 15 set 2025 14:22:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(2150) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `status` CHAR(1) NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(100) NOT NULL,
  `disponivel` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(90) NOT NULL,
  `ingredientes` VARCHAR(300) NOT NULL,
  `valor_un` DECIMAL(10,2) NOT NULL,
  `observacoes` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `idproduto_UNIQUE` (`idproduto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_carrinho` (
  `idcarrinho` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `valor_entrega` DECIMAL(10,2) NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `valor_pago` DECIMAL(10,2) NOT NULL,
  `troco` DECIMAL(10,2) NOT NULL,
  `data_hora` DATETIME NOT NULL,
  PRIMARY KEY (`idcarrinho`),
  UNIQUE INDEX `idcarrinho_UNIQUE` (`idcarrinho` ASC) VISIBLE,
  INDEX `fk_carrinho_cliente_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`tb_cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_entrega` (
  `identrega` INT NOT NULL AUTO_INCREMENT,
  `entregador` VARCHAR(90) NOT NULL,
  `idcarrinho` INT NOT NULL,
  PRIMARY KEY (`identrega`),
  UNIQUE INDEX `identrega_UNIQUE` (`identrega` ASC) VISIBLE,
  INDEX `fk_entrega_carrinho1_idx` (`idcarrinho` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_carrinho1`
    FOREIGN KEY (`idcarrinho`)
    REFERENCES `mydb`.`tb_carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_item_venda` (
  `idcarrinho` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idcarrinho`, `idproduto`),
  INDEX `fk_produto_has_carrinho_carrinho1_idx` (`idcarrinho` ASC) VISIBLE,
  INDEX `fk_produto_has_carrinho_produto1_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_carrinho_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `mydb`.`tb_produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_carrinho_carrinho1`
    FOREIGN KEY (`idcarrinho`)
    REFERENCES `mydb`.`tb_carrinho` (`idcarrinho`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tb_produto (foto, disponivel, tipo, nome, ingredientes, valor_un, observacoes)
VALUES
('bolo_bolodemorango.png', 10, 'Bolo', 'Bolo sabor morango', 'Massa branca, mousse branca, morangos, creme gelado com morangos', 15.00, 'Item popular no cardápio'),
('bolo_ganachelimao.png', 12, 'Bolo', 'Bolo sabor ganache de limão', 'Massa branca, mousse branco, creme gelado de limão', 15.00, 'Refrescante e cítrico'),
('bolo_chocolateamargo.png', 10, 'Bolo', 'Bolo sabor chocolate amargo', 'Massa de chocolate amargo, trufado de chocolate branco, chocolate 100% cacau', 15.00, 'Intenso e sofisticado'),
('bolo_trufadocereja.png', 11, 'Bolo', 'Bolo sabor trufado de cereja', 'Massa de chocolate, mousse de chocolate com cereja, trufado de chocolate ao leite', 15.00, 'Com toque frutado e doce');

INSERT INTO tb_produto (foto, disponivel, tipo, nome, ingredientes, valor_un, observacoes) 
VALUES
('trufa_bolodeaniversario.png', 12, 'Trufa', 'Trufa sabor bolo de aniversário', 'Bolo de baunilha com casca de chocolate branco', 5.00, NULL),
('trufa_chocolateaoleite.png', 13, 'Trufa', 'Trufa sabor chocolate ao leite', 'Ganache cremoso de chocolate ao leite com pedaços de chocolate ao leite', 5.00, NULL),
('trufa_amendoim.png', 11, 'Trufa', 'Trufa sabor amendoim', 'Purê de amendoim com ganache de chocolate, envolto de casca de chocolate', 5.00, NULL),
('trufa_morangocomcreme.png', 12, 'Trufa', 'Trufa sabor morango com creme', 'Mousse de morango e mousse de baunilha em uma casca de chocolate branco', 5.00, NULL),
('trufa_creme.png', 10, 'Trufa', 'Trufa sabor creme', 'Ganache de chocolate amargo e baunilha em uma casca de chocolate branco', 5.00, NULL),
('trufa_chocolateamargo.png', 14, 'Trufa', 'Trufa sabor chocolate amargo', 'Ganache de chocolate amargo com 72% de cacau em uma casca de chocolate amargo', 5.00, NULL);

INSERT INTO tb_produto (foto, disponivel, tipo, nome, ingredientes, valor_un, observacoes) VALUES
('macarons_pistachecomcreme.png', 10, 'Macarons', 'Macaron sabor pistache com creme', 'Massa de pistache com recheio de creme', 6.00, NULL),
('macarons_morangocomcreme.png', 12, 'Macarons', 'Macaron sabor morango com creme', 'Massa de morango com recheio de chocolate branco', 6.00, NULL),
('macarons_baunilha.png', 10, 'Macarons', 'Macaron sabor baunilha', 'Massa de baunilha com creme de baunilha', 6.00, NULL),
('macarons_uva.png', 11, 'Macarons', 'Macaron sabor uva', 'Massa de uva com recheio de mousse de uva', 6.00, NULL),
('macarons_misto.png', 14, 'Macarons', 'Macaron sabor misto', 'Massa de chocolate ao leite com recheio de chocolate branco', 6.00, NULL),
('macarons_limao.png', 10, 'Macarons', 'Macaron sabor limão', 'Massa de limão com recheio de mousse de limão', 6.00, NULL);

INSERT INTO tb_produto (foto, disponivel, tipo, nome, ingredientes, valor_un, observacoes) 
VALUES
('donuts_amendoim.png', 15, 'Donuts', 'Donuts sabor amendoim', 'Rosquinha frita com cobertura de caramelo salgado com amendoins.', 7.00, NULL),
('donuts_chocolatecommorango.png', 15, 'Donuts', 'Donuts sabor chocolate com morango', 'Rosquinha frita com cobertura de brigadeiro e morangos.', 7.00, NULL),
('donuts_laranja.png', 15, 'Donuts', 'Donuts sabor laranja', 'Rosquinha frita com cobertura de geleia de laranja com rodelas de laranja.', 7.00, NULL),
('donuts_leitecondensado.png', 15, 'Donuts', 'Donuts sabor leite condensado', 'Rosquinha frita com cobertura de leite condensado com amoras.', 7.00, NULL),
('donuts_limao.png', 15, 'Donuts', 'Donuts sabor limão', 'Rosquinha frita com cobertura de mousse de limão com rodelas de limão.', 7.00, NULL),
('donuts_uva.png', 15, 'Donuts', 'Donuts sabor uva', 'Rosquinha frita com cobertura de creme de uva com blueberry.', 7.00, NULL);

INSERT INTO tb_produto (foto, disponivel, tipo, nome, ingredientes, valor_un, observacoes) 
VALUES
('cafe_latte.png', 10, 'Café', 'Café sabor latte', 'Café expresso com leite vaporizado e uma fina camada de espuma', 7.00, NULL),
('cafe_flatwhite.png', 10, 'Café', 'Café sabor flat white', 'Café forte e expresso com leite vaporizado e uma fina camada de espuma', 7.00, NULL),
('cafe_capuccino.png', 10, 'Café', 'Café sabor cappuccino', 'Café expresso com uma quantidade pequena de leite vaporizado e uma fina camada de espuma', 7.00, NULL),
('cafe_americano.png', 10, 'Café', 'Café sabor americano', 'Café preto e forte', 7.00, NULL),
('cafe_mocha.png', 10, 'Café', 'Café sabor mocha', 'Café expresso com leite vaporizado, chocolate e uma fina camada de espuma', 7.00, NULL),
('cafe_caramelmachiatto.png', 10, 'Café', 'Café sabor caramel macchiato', 'Xarope de baunilha, leite vaporizado, calda de caramelo e chantilly', 7.00, NULL);

INSERT INTO tb_produto (foto, disponivel, tipo, nome, ingredientes, valor_un, observacoes) 
VALUES
('churros_caramelo.png', 10, 'Churros', 'Churros sabor caramelo', 'Massa tradicional, recheado com caramelo e cobertura de caramelo com castanhas', 12.00, NULL),
('churros_cafe.png', 10, 'Churros', 'Churros sabor café', 'Massa tradicional, recheado com cappuccino e cobertura de doce de leite com gotas de café', 12.00, NULL),
('churros_aoleite.png', 10, 'Churros', 'Churros sabor ao leite', 'Massa tradicional, com recheio e cobertura de brigadeiro com pedaços de barra de chocolate', 12.00, NULL),
('churros_chocolatebranco.png', 10, 'Churros', 'Churros sabor chocolate branco', 'Massa tradicional, recheado com creme e cobertura de chocolate branco e coco', 12.00, NULL),
('churros_limao.png', 10, 'Churros', 'Churros sabor limão', 'Massa tradicional, recheado com mousse de limão e cobertura de geleia de limão com farelo de bolo de limão', 12.00, NULL),
('churros_chocolateamargo.png', 10, 'Churros', 'Churros sabor chocolate amargo', 'Massa tradicional, com recheio e cobertura de brigadeiro 50% com pedaços de barra de chocolate 70%', 12.00, NULL),
('churros_caramelosalgado.png', 10, 'Churros', 'Churros sabor caramelo salgado', 'Massa tradicional, recheado com caramelo salgado e cobertura de chocolate ao leite com nozes', 12.00, NULL),
('churros_pistache.png', 10, 'Churros', 'Churros sabor pistache', 'Massa tradicional, recheado com creme de pistache e cobertura de creme de pistache com pistache', 12.00, NULL),
('churros_morango.png', 10, 'Churros', 'Churros sabor morango', 'Massa tradicional, com recheio e cobertura de morango com farelos de bolo de morango', 12.00, NULL);

INSERT INTO tb_produto (foto, disponivel, tipo, nome, ingredientes, valor_un, observacoes)
VALUES
('cha_graviola.png', 10, 'Chá', 'Chá sabor graviola', 'Gosto natural de folhas de graviola', 5.00, NULL),
('cha_laranja.png', 11, 'Chá', 'Chá sabor laranja', 'Chá de casca de laranja com leve toque cítrico', 5.00, NULL),
('cha_hibiscocafe.png', 12, 'Chá', 'Chá sabor hibisco com café', 'Mistura de hibisco com café torrado, sabor marcante', 5.00, NULL),
('cha_limaohortela.png', 12, 'Chá', 'Chá sabor limão com hortelã', 'Chá refrescante de limão com folhas de hortelã', 5.00, NULL),
('cha_limaolaranja.png', 10, 'Chá', 'Chá sabor limão com laranja', 'Chá cítrico com cascas de limão e laranja', 5.00, NULL),
('cha_maracuja.png', 11, 'Chá', 'Chá sabor maracujá', 'Gosto suave de maracujá com propriedades calmantes', 5.00, NULL);

INSERT INTO tb_produto (foto, disponivel, tipo, nome, ingredientes, valor_un, observacoes) 
VALUES
('milkshake_morango.png', 10, 'Milkshake', 'Milkshake sabor morango', 'Sorvete de creme, calda de morango e leite', 10.00, NULL),
('milkshake_chocolatecookie.png', 10, 'Milkshake', 'Milkshake sabor chocolate cookie', 'Sorvete de chocolate, pedaços de cookie e leite', 10.00, NULL),
('milkshake_oreo.png', 10, 'Milkshake', 'Milkshake sabor Oreo', 'Sorvete de baunilha, biscoito Oreo triturado e leite', 10.00, NULL),
('milkshake_caramelo.png', 10, 'Milkshake', 'Milkshake sabor caramelo', 'Sorvete de creme, calda de caramelo e leite', 10.00, NULL),
('milkshake_sensacao.png', 10, 'Milkshake', 'Milkshake sabor sensação', 'Sorvete de morango, calda de chocolate e leite', 10.00, NULL),
('milkshake_pudim.png', 10, 'Milkshake', 'Milkshake sabor pudim', 'Sorvete de creme, pedaços de pudim e calda de caramelo', 10.00, NULL);




INSERT INTO tb_cliente (email, senha, nome, telefone, endereco, status, tipo) 
VALUES 
  ('Todyy@gmail.com', SHA2('todyy', 256), 'Iasmin', '123456789', 'rua 2314', 'd', 'c'),
  ('lucas@gmail.com', SHA2('lucas', 256), 'Lucas Silva', '987654321', 'av. Paulista, 1500', 'd', 'c'),
  ('jose@example.com', SHA2('jose', 256), 'José Pereira', '1122334455', 'rua 4567', 'd', 'c'),
  ('mariana@hotmail.com', SHA2('mariana', 256), 'Mariana Costa', '9988776655', 'rua das Flores, 1000', 'd', 'c'),
  ('bruna@outlook.com', SHA2('bruna', 256), 'Bruna Almeida', '6677889900', 'av. Rio Branco, 200', 'd', 'c'),
  ('fabio@site.com', SHA2('fabio', 256), 'Fábio Costa', '5556667777', 'rua Jardim, 32', 'd', 'c'),
  ('camila@dominio.com', SHA2('camila', 256), 'Camila Souza', '4445556666', 'rua do Sol, 850', 'd', 'c'),
  ('pedro@exemplo.com', SHA2('pedro', 256), 'Pedro Lima', '3334445555', 'av. Central, 50', 'd', 'c'),
  ('ana@teste.com', SHA2('ana', 256), 'Ana Oliveira', '2223334444', 'rua das Palmeiras, 22', 'd', 'c'),
  ('roberto@company.com', SHA2('roberto', 256), 'Roberto Martins', '1212121212', 'rua do Parque, 123', 'd', 'c'),
  ('larissa@webmail.com', SHA2('larissa', 256), 'Larissa Santos', '1987654321', 'av. Brasil, 750', 'd', 'c'),
  ('andrea@admin.com', SHA2('andrea', 256), 'Andrea Silva', '6667778888', 'rua dos Gestores, 11', 'd', 'g'),
  ('rodrigo@manager.com', SHA2('rodrigo', 256), 'Rodrigo Carvalho', '9998887777', 'av. Empresarial, 40', 'd', 'g'),
  ('patricia@corporate.com', SHA2('patricia', 256), 'Patricia Gomes', '5557779999', 'rua Executiva, 78', 'd', 'g'),
  ('alex@adminsite.com', SHA2('alex', 256), 'Alex Ferreira', '4448887777', 'av. Liderança, 50', 'd', 'g'),
  ('toddy@gmail.com', SHA2('toddy', 256), 'Iasminny', '4228887777', 'av. Onçinha, 59', 'd', 'g'),
  ('sandy@gmail.com', SHA2('sandy', 256), 'Sandy', '444845377', 'av Barracão, 50', 'd', 'g'),
  ('izabella@gmail.com', SHA2('izabella', 256), 'Izabella', '4446687777', 'rua itiopo, 50', 'd', 'g');
